import type { LevelConfig } from '@/types/game';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: '入职培训',
    theme: '新手幻觉',
    description: '今天是你的第一天。系统提示你：请遵守交规，安全送达。',
    targetOrders: 2,
    rentCost: 50,
    mapWidth: 2000,
    mapHeight: 2000,
    intersections: 4,
    oneWayStreets: false,
    baseTime: 120,
    trafficDensity: 0.15,
    redLightDuration: 8,
    greenLightDuration: 10,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 1,
    truckEnabled: false,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '欢迎加入极速配送！今天是你入职第一天。', isSystem: true },
      { speaker: '系统', text: '请遵守交通规则，安全送达每一单。', isSystem: true },
      { speaker: '站长', text: '新人啊，听好了，这行很简单——快就完事了。' },
      { speaker: '站长', text: '等红灯？那是给有闲人等的东西。', isSystem: false },
    ],
    endingDialogue: [
      { speaker: '系统', text: '今日工作完成。收入结算中...', isSystem: true },
      { speaker: '系统', text: '表现良好，明天继续加油！', isSystem: true },
    ],
  },
  {
    id: 2,
    name: '绩效初现',
    theme: '捷径诱惑',
    description: '你发现了一条小巷，可以抄近道...但这条巷子是单行道。',
    targetOrders: 3,
    rentCost: 80,
    mapWidth: 2400,
    mapHeight: 2400,
    intersections: 3,
    oneWayStreets: true,
    baseTime: 100,
    trafficDensity: 0.2,
    redLightDuration: 10,
    greenLightDuration: 8,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 1,
    specialMechanic: '逆行小巷',
    truckEnabled: false,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '检测到您配送效率有待提升。', isSystem: true },
      { speaker: '系统', text: '已为您规划逆行最优路线！可节省30%时间！', isSystem: true },
      { speaker: '老骑手', text: '兄弟，走那条小巷，快得很。' },
      { speaker: '老骑手', text: '单行道？谁管啊，交警又不会天天来。' },
    ],
    endingDialogue: [
      { speaker: '系统', text: '配送效率提升15%！系统奖励您"速度先锋"徽章！', isSystem: true },
    ],
  },
  {
    id: 3,
    name: '算法收紧',
    theme: '双单压力',
    description: '系统同时派给你两单，两个顾客在不同方向。等红灯意味着两单同时超时。',
    targetOrders: 4,
    rentCost: 120,
    mapWidth: 2800,
    mapHeight: 2800,
    intersections: 4,
    oneWayStreets: false,
    baseTime: 80,
    trafficDensity: 0.35,
    redLightDuration: 12,
    greenLightDuration: 6,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 2,
    truckEnabled: false,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '午高峰已开启！订单量激增！', isSystem: true },
      { speaker: '系统', text: '已为您同时派发2个订单，请合理规划路线。', isSystem: true },
      { speaker: '顾客A', text: '我的外卖怎么还没到？都半小时了！' },
      { speaker: '顾客B', text: '再不来我就投诉你！' },
    ],
    endingDialogue: [
      { speaker: '系统', text: '双单处理能力解锁！您的抗压能力令人赞叹。', isSystem: true },
    ],
  },
  {
    id: 4,
    name: '恶劣天气',
    theme: '物理恶化',
    description: '下雨了。路面湿滑，刹车距离变长。视野变差。',
    targetOrders: 5,
    rentCost: 150,
    mapWidth: 2800,
    mapHeight: 2800,
    intersections: 4,
    oneWayStreets: false,
    baseTime: 80,
    trafficDensity: 0.45,
    redLightDuration: 12,
    greenLightDuration: 6,
    yellowLightDuration: 2,
    weather: 'RAIN',
    maxConcurrentOrders: 2,
    truckEnabled: false,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '暴雨预警！请骑手注意安全配送！', isSystem: true },
      { speaker: '系统', text: '恶劣天气配送补贴已发放：每单+1元。', isSystem: true },
      { speaker: '天气', text: '雨水模糊了视线，路面像抹了油。', isSystem: false },
    ],
    endingDialogue: [
      { speaker: '系统', text: '雨天的磨砺让您更加强大！', isSystem: true },
    ],
  },
  {
    id: 5,
    name: '午高峰修罗场',
    theme: '十字路口',
    description: '红灯长达20秒，绿灯只有5秒。不闯红灯，不可能完成任务。',
    targetOrders: 6,
    rentCost: 200,
    mapWidth: 3200,
    mapHeight: 3200,
    intersections: 6,
    oneWayStreets: false,
    baseTime: 60,
    trafficDensity: 0.7,
    redLightDuration: 18,
    greenLightDuration: 5,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 2,
    truckEnabled: true,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '午高峰S级预警！全城爆单！', isSystem: true },
      { speaker: '系统', text: '您本月绩效已跌至末位10%，请注意！', isSystem: true },
      { speaker: '站长', text: '今天送不完12单，明天不用来了。' },
      { speaker: '系统', text: 'Top骑手从不等红灯！他们正在创造历史！', isSystem: true },
    ],
    endingDialogue: [
      { speaker: '系统', text: '恭喜您在午高峰中幸存！', isSystem: true },
      { speaker: '系统', text: '闯红灯次数已刷新您的个人记录！', isSystem: true },
    ],
  },
  {
    id: 6,
    name: '周一',
    theme: '压力累积',
    description: '渣土车出现了。碰到就是死。房租又涨了。',
    targetOrders: 6,
    rentCost: 250,
    mapWidth: 3200,
    mapHeight: 3200,
    intersections: 5,
    oneWayStreets: true,
    baseTime: 65,
    trafficDensity: 0.5,
    redLightDuration: 15,
    greenLightDuration: 5,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 2,
    truckEnabled: true,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '新的一周开始了！房租已自动扣除。', isSystem: true },
      { speaker: '系统', text: '注意：渣土车出没路段增加，请保持警惕。', isSystem: true },
      { speaker: '房东', text: '下个月房租涨50，爱住不住。' },
    ],
    endingDialogue: [
      { speaker: '系统', text: '周一小结：您的违规率上升了200%。', isSystem: true },
    ],
  },
  {
    id: 7,
    name: '周三',
    theme: '临界点',
    description: '周中，疲惫累积。交警开始在路口蹲守。',
    targetOrders: 7,
    rentCost: 300,
    mapWidth: 3600,
    mapHeight: 3600,
    intersections: 6,
    oneWayStreets: false,
    baseTime: 55,
    trafficDensity: 0.6,
    redLightDuration: 16,
    greenLightDuration: 5,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 2,
    specialMechanic: '交警抽查',
    truckEnabled: true,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '温馨提示：近期交警严查闯红灯行为。', isSystem: true },
      { speaker: '系统', text: '被抓到罚款200元。祝您好运。', isSystem: true },
      { speaker: '骑手群', text: '路口有交警，大家注意！', isSystem: false },
      { speaker: '骑手群', text: '但别太慢啊，单子要超时了...', isSystem: false },
    ],
    endingDialogue: [
      { speaker: '系统', text: '周三过半，周末遥遥无期。', isSystem: true },
    ],
  },
  {
    id: 8,
    name: '周五',
    theme: '极限压榨',
    description: '夜晚。3单同时派发。你必须在车辆的夹缝中求生。',
    targetOrders: 8,
    rentCost: 350,
    mapWidth: 4000,
    mapHeight: 4000,
    intersections: 8,
    oneWayStreets: true,
    baseTime: 50,
    trafficDensity: 0.8,
    redLightDuration: 18,
    greenLightDuration: 4,
    yellowLightDuration: 2,
    weather: 'NIGHT',
    maxConcurrentOrders: 3,
    truckEnabled: true,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '周五狂欢夜！订单爆炸！', isSystem: true },
      { speaker: '系统', text: '同时为您派发3个订单！这是平台对您的信任！', isSystem: true },
      { speaker: '站长', text: '今晚送完这15单，给你发100块奖金。' },
      { speaker: '站长', text: '送不完？奖金没有，还要扣你培训费。' },
    ],
    endingDialogue: [
      { speaker: '系统', text: '周五结束了。您还活着，真是个奇迹。', isSystem: true },
    ],
  },
  {
    id: 9,
    name: '周末',
    theme: '虚假希望',
    description: '你以为周末能休息？不，周末是最高密度。',
    targetOrders: 9,
    rentCost: 400,
    mapWidth: 4000,
    mapHeight: 4000,
    intersections: 8,
    oneWayStreets: false,
    baseTime: 45,
    trafficDensity: 0.9,
    redLightDuration: 15,
    greenLightDuration: 5,
    yellowLightDuration: 2,
    weather: 'CLEAR',
    maxConcurrentOrders: 3,
    truckEnabled: true,
    showTimer: true,
    openingDialogue: [
      { speaker: '系统', text: '周末爆单模式已启动！', isSystem: true },
      { speaker: '系统', text: '您的同事都已上线，竞争排名开始！', isSystem: true },
      { speaker: '系统', text: '目前排名：第128名。冲进前100可获得"铁人"称号！', isSystem: true },
      { speaker: '身体', text: '你的双手在颤抖，眼睛布满血丝。', isSystem: false },
    ],
    endingDialogue: [
      { speaker: '系统', text: '周末结算：您本周闯红灯47次。', isSystem: true },
      { speaker: '系统', text: '但您赚了足够的房租！恭喜！', isSystem: true },
    ],
  },
  {
    id: 10,
    name: '生存还是毁灭',
    theme: '终极拷问',
    description: '没有倒计时了。只有顾客不断的催命消息。你能不闯红灯就完成任务吗？',
    targetOrders: 10,
    rentCost: 500,
    mapWidth: 4800,
    mapHeight: 4800,
    intersections: 10,
    oneWayStreets: true,
    baseTime: 9999,
    trafficDensity: 1.0,
    redLightDuration: 22,
    greenLightDuration: 4,
    yellowLightDuration: 2,
    weather: 'NIGHT',
    maxConcurrentOrders: 3,
    truckEnabled: true,
    showTimer: false,
    openingDialogue: [
      { speaker: '系统', text: '最终考核日。', isSystem: true },
      { speaker: '系统', text: '倒计时已隐藏。请凭感觉配送。', isSystem: true },
      { speaker: '顾客', text: '快饿死了！！！！' },
      { speaker: '顾客', text: '你怎么还没来？？？' },
      { speaker: '顾客', text: '我要投诉你！！！' },
      { speaker: '系统', text: '您在思考：等红灯是对的吗？', isSystem: true },
      { speaker: '系统', text: '如果每个人都等红灯，这个世界会停摆。', isSystem: true },
    ],
    endingDialogue: [
      { speaker: '系统', text: '游戏结束了。', isSystem: true },
      { speaker: '系统', text: '但这真的只是一个游戏吗？', isSystem: true },
    ],
  },
];
